config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources 'users', only: ['create', 'update'] do
    collection do
      get '/me', action: 'show_authenticated_user'
      get '/check_email', action: 'check_email'
      get '/reset_password', action: 'reset_password'
      post '/change_password', action: 'change_password'
      get '/me/widgets', action: 'private_widgets', as: 'my_widgets'
      post '/sign_in', action: 'sign_in'
      get '/sign_out', action: 'sign_out'
      get '/:id', action: 'show_user_by_id', as: 'by_id'
      get '/:id/widgets', action: 'widgets_by_user_id'
    end
  end

  resources 'widgets', only: ['index', 'create', 'update', 'destroy'] do
    get '/visible', action: 'visible', on: :collection
  end

  namespace 'auths' do
    post '/create', action: 'create'
    post '/refresh', action: 'refresh'
    post '/revoke', action: 'revoke'
  end

  root 'widgets#visible'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <a class="navbar-brand" href="/">Showoff</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <% if user_authenticated? %>
        <li class="nav-item">
          <%= link_to "Me", me_users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Widgets", my_widgets_users_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <% if user_authenticated? %>
        <ul class="navbar-nav my-2 my-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Reset Pass", reset_password_users_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", sign_out_users_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% else %>
        <button type="button" class="btn btn-outline-secondary my-2 my-lg-0 mr-1" data-toggle="modal" data-target="#signInModal">
          Sign In
        </button>
        <button type="button" class="btn btn-secondary my-2 my-lg-0" data-toggle="modal" data-target="#signUpModal">
          Sign Up
        </button>
      <% end %>
    </div>
  </div>
</nav>

<!-- Modals -->
<div class="modal" id="signInModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sign In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :user, url: sign_in_users_path do |f| %>
          <div>
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <div class="mt-3 float-right">
            <%= f.submit "Sign In", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="signUpModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sign Up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :user, url: users_path do |f| %>
          <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <div class="mt-3 float-right">
            <%= f.submit "Sign Up", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="changePassModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sign Up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :user, url: users_path do |f| %>
          <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control mb-1" %>
          </div>
          <div>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <div class="mt-3 float-right">
            <%= f.submit "Sign Up", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>