config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources 'users', only: ['create', 'update'] do
    collection do
      get '/me', action: 'show_authenticated_user'
      get '/check_email', action: 'check_email'
      get '/reset_password', action: 'reset_password'
      post '/change_password', action: 'change_password'
      get '/me/widgets', action: 'private_widgets', as: 'my_widgets'
      post '/sign_in', action: 'sign_in'
      get '/sign_out', action: 'sign_out'
      get '/:id', action: 'show_user_by_id', as: 'by_id'
      get '/:id/widgets', action: 'widgets_by_user_id'
    end
  end

  resources 'widgets', only: ['index', 'create', 'update', 'destroy'] do
    get '/visible', action: 'visible', on: :collection
  end

  namespace 'auths' do
    post '/create', action: 'create'
    post '/refresh', action: 'refresh'
    post '/revoke', action: 'revoke'
  end

  root 'widgets#visible'
end

app/models/widget.rb
class Widget < ApplicationModel
  attr_accessor :id,
                :name,
                :description,
                :kind,
                :new_record,
                :user_token,
                :response

  alias token user_token
  alias errors response

  include UserBelonging

  def save
    success, self.response = if new_record
                               WidgetService.create_widget(self)
                             else
                               WidgetService.update_widget(self)
                             end
    self.id = response.dig('data', 'widget', 'id') if success && new_record
    success
  end

  def delete_widget
    success, self.response = WidgetService.delete_widget(self)
    success
  end

  def public_widgets
    success, self.response = WidgetService.public_widgets(self)
    success
  end

  def visible_widgets(search_term = nil)
    success, self.response = WidgetService.visible_widgets(search_term)
    success
  end

  def reload
    response.dig('data', 'widget')&.each do |attr, value|
      try("#{attr}=", value)
    end
  end
end

app/controllers/widgets_controller.rb
# frozen_string_literal: true

class WidgetsController < ApplicationController
  before_action :set_widget, :set_user_token

  def index
    if @widget.public_widgets
      render json: @widget.response, status: :ok
    else
      render json: @widget.errors, status: :conflict
    end
  end

  def visible
    search_term = params[:search_term]

    if @widget.visible_widgets(search_term)
      respond_to do |format|
        format.html { @widgets = helpers.prepare_for_collection(@widget) }
        format.json { render json: @widget.response, status: :ok }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = @widget.errors['message']
          redirect_to root_path
        end
        format.json { render json: @widget.errors, status: :conflict }
      end
    end
  end

  def create
    @widget.new_record = true

    if @widget.save
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.json { render json: @widget.response, status: :ok }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = @widget.errors['message']
          redirect_back fallback_location: root_path
        end
        format.json { render json: @widget.errors, status: :conflict }
      end
    end
  end

  def update
    @widget.id = params[:id]
    @widget.new_record = false

    if @widget.save
      render json: @widget.response, status: :ok
    else
      render json: @widget.errors, status: :conflict
    end
  end

  def destroy
    @widget.id = params[:id]
    if @widget.delete_widget
      render json: @widget.response, status: :ok
    else
      render json: @widget.errors, status: :conflict
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_widget
    @widget = begin
                Widget.new(widget_params)
              rescue StandardError
                Widget.new
              end
  end

  def set_user_token
    @widget.user_token = session[:token] if @widget.user_token.nil?
  end

  # Only allow a list of trusted parameters through.
  def widget_params
    params.require(:widget).permit(:id, :name, :description, :kind, :user_token) || {}
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_for :widget, url: widgets_path do |f| %>
  <div>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control mb-1" %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control mb-1" %>
    </div>
    <div>
      <%= f.label :kind %>
      <%= f.select :kind, [['Hidden', 'hidden'], ['Visible', 'visible']], {}, {class: "form-control mb-1"} %>
    </div>

    <div class="float-right mt-3">
      <%= f.submit "Create", class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/widgets/_index.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Kind</th>
    <th scope="col">User ID</th>
  </tr>
  </thead>
  <tbody>
  <% @widgets.each do |widget| %>
    <tr>
      <th scope="row"><%= widget.id %></th>
      <td><%= widget.name.truncate(20) %></td>
      <td><%= widget.description.truncate(50) %></td>
      <td><span class="<%= badge_class(widget.kind) %>"><%= widget.kind.capitalize %></span></td>
      <td><%= link_to widget.user.id, by_id_users_path(widget.user.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/widgets/_search.html.erb
<%= form_tag(visible_widgets_path, method: :get, enforce_utf8: false, class: 'form-inline my-2 my-lg-0') do %>
  <%= text_field_tag(:search_term, params[:search_term], class: 'form-control mr-sm-2', type: 'text', placeholder: 'Search') %>
  <%= submit_tag('Search', name: nil, class: 'btn btn-outline-secondary my-2 my-sm-0') %>
<% end %>

app/views/widgets/visible.html.erb
<div class="mt-5 mb-5">
  <%= render 'search' %>
</div>

<div class="mt-5 mb-5">
  <%= render 'index' %>
</div>